#!/usr/bin/env python

"""Amulet tests on a basic congress deployment on artful-pike.
"""

from basic_deployment import CongressBasicDeployment

if __name__ == '__main__':
    deployment = CongressBasicDeployment(series='artful')
    deployment.run_tests()
